# -*- coding: utf-8 -*-
"""J.Pak . Assignment 3 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCfIgGuB3qpLdWLRXtyTpmjp8gUJk78Z
"""

# 1. Write a Python program to print the following string in a specific format (see the
# output).

# Twinkle, twinkle, little star,
# How I wonder what you are!
# Up above the world so high,
# Like a diamond in the sky.

# Twinkle, twinkle, little star,
# How I wonder what you are


def print_twinkle():
    lines = [
        "Twinkle, twinkle, little star,",
        "                  How I wonder what you are!",
        "                              Up above the world so high,",
        "                              Like a diamond in the sky.",
        "Twinkle, twinkle, little star,",
        "                  How I wonder what you are!",
    ]

    for line in lines:
        print(line)
    print()

print_twinkle()

# 2. Write a Python program to get the Python version you are using

import sys

def get_python_version():
    return sys.version

print("Python Version:", get_python_version())


# 3. Write a Python program to display the current date and time.

from datetime import datetime

def display_current_date_time():
    current_datetime = datetime.now()
    formatted_datetime = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
    print("Current Date and Time:", formatted_datetime)

display_current_date_time()

# 4. Write a Python program which accepts the radius of a circle from the user and compute the area.
def compute_circle_area(radius):
    pi = 3.14159
    area = pi * radius ** 2
    return area

def main():
    try:
        radius = float(input("Enter the radius of the circle: "))
        area = compute_circle_area(radius)
        print(f"The area of the circle with radius {radius} is: {area:.2f}")
    except ValueError:
        print("Error: Please enter a valid number for the radius.")

if __name__ == "__main__":
    main()

# 5. Write a Python program which accepts the user's first and last name and print them in
# reverse order with a space between them.
def main():
    first_name = input("Enter your first name: ")
    last_name = input("Enter your last name: ")

    full_name = f"{last_name} {first_name}"
    print("Reversed name:", full_name)

if __name__ == "__main__":
    main()

# 6. Write a python program which takes two inputs from user and print them addition
def main():
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))

        addition = num1 + num2
        print("The addition of", num1, "and", num2, "is:", addition)
    except ValueError:
        print("Error: Please enter valid numbers.")

if __name__ == "__main__":
    main()

# 7. Write a program which takes 5 inputs from user for different subject’s marks, total it
# and generate mark sheet using grades?

def calculate_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F"

def main():
    try:
        marks = []
        total_marks = 0

        for i in range(5):
            subject_mark = float(input(f"Enter the marks for subject {i + 1}: "))
            marks.append(subject_mark)
            total_marks += subject_mark

        percentage = (total_marks / (5 * 100)) * 100
        grade = calculate_grade(percentage)

        print("\n------- Mark Sheet -------")
        for i in range(5):
            print(f"Subject {i + 1}: {marks[i]}")
        print(f"Total Marks: {total_marks}")
        print(f"Percentage: {percentage:.2f}%")
        print(f"Grade: {grade}")

    except ValueError:
        print("Error: Please enter valid numeric marks.")

if __name__ == "__main__":
    main()

# 8. Write a program which take input from user and identify that the given number is even
# or odd?

def check_even_odd(number):
    if number % 2 == 0:
        return "even"
    else:
        return "odd"

def main():
    try:
        num = int(input("Enter a number: "))
        result = check_even_odd(num)
        print(f"The number {num} is {result}.")
    except ValueError:
        print("Error: Please enter a valid integer.")

if __name__ == "__main__":
    main()


# 9. Write a program which print the length of the list?
def main():
    my_list = [1, 2, 3, 4, 5, "a", "b", "c"]
    list_length = len(my_list)
    print("The length of the list is:", list_length)

if __name__ == "__main__":
    main()

# 10.Write a Python program to sum all the numeric items in a list?
def sum_numeric_items(my_list):
    total = 0
    for item in my_list:
        if isinstance(item, (int, float)):
            total += item
    return total

def main():
    my_list = [1, 2, 3, 4, 5, "a", "b", 6.5, 7.5, 8.5]
    result = sum_numeric_items(my_list)
    print("The sum of numeric items in the list is:", result)

if __name__ == "__main__":
    main()

# 11.Write a Python program to get the largest number from a numeric list.
def get_largest_number(my_list):
    if not my_list:
        return None

    largest_number = my_list[0]
    for number in my_list:
        if number > largest_number:
            largest_number = number

    return largest_number

def main():
    my_list = [10, 5, 25, 8, 30, 15]
    largest_number = get_largest_number(my_list)

    if largest_number is not None:
        print("The largest number in the list is:", largest_number)
    else:
        print("The list is empty.")

if __name__ == "__main__":
    main()


# 12. Take a list, say for example this one:
# a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
# Write a program that prints out all the elements of the list that are less than 5.

def main():
    a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
    less_than_5 = [num for num in a if num < 5]

    print("Elements less than 5 in the list:")
    for num in less_than_5:
        print(num)

if __name__ == "__main__":
    main()